### ISSUE TITLE
unable to delete old SOUP v1.10.0 without deleting both v2.0 as well

### ISSUE THREAD

**Issue by ericfont** [theukedge/soup-show-off-upcoming-posts#16]
I logged into my wordpress, and saw that SOUP had an update, so I updated it.  But then after I updated it, I noticed that there are two version of SOUP in my /wp-admin/plugins.php as shown below:
![wp-admin-plugins-old-soup](https://cloud.githubusercontent.com/assets/6502474/10382885/be88162a-6df6-11e5-8d4c-4108f7af7947.png)

if I try to delete the old v1.10.0, then my wp-admin tries to delete both versions:

![try-to-delete-soup](https://cloud.githubusercontent.com/assets/6502474/10382942/5140e078-6df7-11e5-870f-775e64fd0302.png)

 even though I only selected the old one to be deleted.  If I do goahed with the delete, it does delete both, but then after reinstalling the latest SOUP by going to wp-admin/plugin-install.php and searching for latest SOUP, somehow both versions get installed again.

I don't remember doing anything unusual with my install (I only go through the official wp-admin plugin search & install, instead of doing manually uploading a zip).  Maybe there is some rookie mistake I've made.

**Comment by theukedge** [comment]
Eric,

Thanks for bringing this up. This is a weird bug that was introduced as a result of changing the plugin's main file name (in preparation for wordpress.org language packs). For some reason, even though the old main file wasn't present in the update, it still kept it in place, causing there to be two versions of the plugin being in place effectively.

I provided a fix [here](https://wordpress.org/support/topic/2-diffrent-versions-of-soup-installed-at-the-same-time). Let me know if that doesn't do it for you.

**Comment by ericfont** [comment]
fix worked, thanks.
