### ISSUE TITLE
Overly complicated configuration

### ISSUE THREAD

**Issue by workabyte** [theukedge/soup-show-off-upcoming-posts#18]
So i see in the logs that options to just pick Drafts / Scheduled posts was removed to allow for a more robust configuration using the filter options.

I wonder if we can find a middle ground on this, I am a developer but not a PHP dev or a wordpress dev. Could i figure it out, sure. Will I, maybe. My blog is not designed to be something i have to work on, I choose wordpress becauuse its effortless.

I can see the advantage in the direction you are going but i would guess that 90% or more of your users will want the simple options, scheduled posts/Drafts/both.

Maybe there can be a setting that allows for that or the option to use the more involved filters?
Maybe there can be a more complete How To on setting up filters for those options?

Thank you for an awesome plugin, hope this helps to polish it a bit.

**Comment by theukedge** [comment]
Thanks for your suggestion. I think that this is the right approach. Frankly, I started adding those options as requests for further configuration started to come in and there's no limit to how many options I could create to meet every need. So in the spirit of [Decisions, Not Options](https://wordpress.org/about/philosophy/#decisions), I think that adding the filter to the query args is the best way to allow everyone to add the customisations that they want without bloating the widget with every conceivable configuration.
