### ISSUE TITLE
We're out of SOUP

### ISSUE THREAD

**Issue by GaryBartlett** [theukedge/soup-show-off-upcoming-posts#21]
Hi Dave,

Thanks for the plugin.  It was easy to install - and just worked.

However, after the latest update, it stopped working on my site http://prodsol.com/blog.  The upcoming section just disappeared from the front-end.

I haven't customised anything and have made no changes since running the update, except to edit and change the schedule on a post that went live 40 minutes or so ago.

I deactivated and activated to no avail.

Has anyone else experienced the same issue?

I'm happy to provide you with admin access to the site if it would help.

Thanks

Gary

**Comment by theukedge** [comment]
I haven't heard of anyone having any issues, but I'm happy to take a quick look. Feel free to send an admin login to me [here](https://www.theukedge.com/#contact).

**Comment by theukedge** [comment]
Discussed with user and this was an issue unrelated to the plugin itself.

**Comment by GaryBartlett** [comment]
Great service - thanks, Dave!
