### ISSUE TITLE
Upcoming posts only showing to admin users

### ISSUE THREAD

**Issue by annemcclane** [theukedge/soup-show-off-upcoming-posts#22]
The upcoming posts aren't showing for "subscriber" users, only admin users. For "subscribers" it just shows "More to come" as if there are no upcoming posts.

This is on a membership website.

**Comment by theukedge** [comment]
Anne,

The plugin itself doesn't look at the user role whatsoever, so I'm thinking that the most likely explanation is that either caching is causing old information to be displayed, or that the posts are private or something, meaning that only admins can see them, so when a subscriber is logged in, they don't see these private posts.
