### ISSUE TITLE
Feature Request: Include formatted publish date in text for each upcoming post

### ISSUE THREAD

**Issue by ericfont** [theukedge/soup-show-off-upcoming-posts#7]
It would be nice to have the option, maybe as a checkbox in the configuration, to include the date/time of publication inside the text of each upcoming post.  Also maybe have option to select different datetime formats.

**Comment by theukedge** [comment]
I quite like this idea and am not sure why I haven't done this sooner. I'll build this in.

**Comment by theukedge** [comment]
Closed by 5f8f889a27a13cc7f76237b8af4a8b3e1170a45e

**Comment by ericfont** [comment]
thanks!

**Comment by ericfont** [comment]
Seems to work, except if my post title already has a parenthesis in it, then no date is shown. Is this desired behavior?

**Comment by theukedge** [comment]
No, that's bizarre, let me do some testing on it. The post title and post date are independent functions being called in this case, so they shouldn't affect one another.

**Comment by theukedge** [comment]
I couldn't replicate this behaviour. When I used post titles with parantheses in them, they still worked the same, as predicted.

**Comment by ericfont** [comment]
ok, I can't seem to replicate now either...it must have been something else going on...I'll let you know if find exact replication steps.
