### ISSUE TITLE
option to make upcoming post text a hyperlink pointing to the post url (even if not published)

### ISSUE THREAD

**Issue by ericfont** [theukedge/soup-show-off-upcoming-posts#8]
I have been using your plugin in conjunction with "Future" plugin (https://wordpress.org/plugins/future/ which essentially makes future scheduled posts to be viewable and allows them to be integrated into the wordpress calendar widget).  I'd like the option to be able to have SOUP treat the text for each post title as a hyperlink pointing to the url where the post will be published.

**Comment by theukedge** [comment]
I think that since this is something of an edge case, I won't be implementing this option in favour of [decisions, not options](https://wordpress.org/about/philosophy/#decisions). Thanks for the suggestion

**Comment by ericfont** [comment]
I understand.  Thanks for pointing me to that philosophy page.  I will try to figure out a workaround.
