### ISSUE TITLE
SOUP is showing posts that went live years ago

### ISSUE THREAD

**Issue by wgshef** [theukedge/soup-show-off-upcoming-posts#9]
Currently using version 1.9. SOUP is showing posts that were published 3-4 years ago, instead of posts that are scheduled.

**Comment by theukedge** [comment]
I've had a few people comment on this recently. Apparently, either removing the widget and reinstalling it, or deactivating and reactivating the plugin fixes it. Let me know what you find.

**Comment by wgshef** [comment]
Deactivating / reactivating did NOT fix it.
Removing widget, saving, adding widget back, saving did fix it.

Now on 1.10. I like having the date in there also.

**Comment by theukedge** [comment]
Thanks for letting me know how it went and how you got it working again. Glad you like v1.10.0
